default:
  image: archlinux

before_script:
    - pacman -Syyuu --noconfirm cmake make gcc git
    - git submodule update --init engi_common
    - git submodule update --remote --recursive engi_common

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_ASAN=ON -B build/
    - cmake --build build/
    - echo "Compile complete."

test-job:
  stage: test
  script:
    - ./engi_queue_static_test
    - ./engi_queue_shared_test