default:
  image: archlinux

before_script:
    - pacman -Syyuu --noconfirm cmake make gcc git
    - git submodule update --init --remote --recursive

stages:
  - build
  - test
  
build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_ASAN=ON -B build/
    - cmake --build build/
    - echo "Compile complete."
  artifacts:
    paths:
      - build/libengi_queue.so
      - build/libengi_queue.a
      - build/engi_queue_static_test
      - build/engi_queue_shared_test

test-job:
  stage: test
  script:
    - ./build/engi_queue_static_test
    - ./build/engi_queue_shared_test
