default:
  image: archlinux

before_script:
    - pacman -Syyuu --noconfirm cmake make gcc git
    - git submodule update --init --remote --recursive

stages:
  - dependency
  - build
  - test
  
dependency-job:
  stage: dependency
  script:
    - echo "Downloading dependecies"
    - cd ..
    - git clone --depth=1 https://gitlab.com/malformed-c/engi_common.git
    - echo "Done"
  artifacts:
    untracked: true
    when: on_success
    expire_in: 30 days
    paths:
      - "../engi_common"

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_ASAN=ON -B build/
    - cmake --build build/
    - echo "Compile complete."
  artifacts:
    paths:
      - build/libengi_queue.so
      - build/libengi_queue.a
      - build/engi_queue_static_test
      - build/engi_queue_shared_test
  cache:
    paths:
      - "build/CMakeFiles"
      - "build/CMakeCache.txt"


test-job:
  stage: test
  script:
    - ./build/engi_queue_static_test
    - ./build/engi_queue_shared_test
